# Generated by Django 3.2.12 on 2022-10-25 18:52

import itertools
from django.db import migrations


def create_company(apps, schema_editor):
    linde = ['BC Garn', 'Cewec', 'Dale Garn', 'DMC', 'Du Store Alpakka',
             'Gjestal', 'Go Handmade', 'Hjertegarn', 'Hoooked', 'Istex',
             'Järbo', 'Katia', 'KnitAtHome', 'Kremke Soul Wool', 'Lammy',
             'Lana Grossa', 'Malabrigo', 'Manos del Uruguay', 'Mayflower',
             'Natural Club', 'Navia', 'Onion', 'Opal', 'Permin', 'Phildar',
             'Regia', 'Rico Design', 'Rowan', 'Scheepjes', 'Svarta Fåret',
             'Viking', 'Yarn And Colors']
    hobbii = ['Friends', 'Happy Sheep', 'Hobbii', 'Madeira', 'We Love Yarn',
              'World of Yarn', 'Andersen', 'Bumbo', 'Cotton Kings', 'DMC',
              'Go Handmade', 'Hjertegarn', 'Järbo', 'Kremke Soul Wool',
              'Mayflower', 'Navia', 'Viking', 'BC Garn']
    companies = []

    Company = apps.get_model('ravelry', 'Company')

    for i in itertools.chain(linde, hobbii):
        in_linde = i in linde
        in_hobbii = i in hobbii
        companies.append(
            Company(name=i, linde_hobby=in_linde, hobbii=in_hobbii))

    Company.objects.bulk_create(companies)


class Migration(migrations.Migration):

    dependencies = [
        ('ravelry', '0002_auto_20221025_1850'),
    ]

    operations = [
        migrations.RunPython(create_company)
    ]
