# Generated by Django 3.2.12 on 2022-10-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravelry', '0003_auto_20221025_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='yarn',
            name='texture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
