# Generated by Django 3.2.12 on 2022-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravelry', '0004_auto_20221026_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
