# Generated by Django 3.2.12 on 2022-11-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravelry', '0005_yarn_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='gauge_divisor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='grams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='max_gauge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='min_gauge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='texture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='yardage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
